// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathOrderManagement.DataAccess;

#nullable disable

namespace PathOrderManagement.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220513012820_add-category-cargo-table")]
    partial class addcategorycargotable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("OrderID");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CargoCompanies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9054e8d2-8af6-431c-aaad-f83abc441075"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 11, DateTimeKind.Local).AddTicks(2114),
                            Name = "Yurtiçi Kargo"
                        },
                        new
                        {
                            Id = new Guid("f7866ba0-eaa6-409a-b3a3-50395ea3453e"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 11, DateTimeKind.Local).AddTicks(2424),
                            Name = "Aras Kargo"
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CategoryCargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CategoryCargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a73c9dc-1c20-480f-8e1c-19e2270b437f"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 10, DateTimeKind.Local).AddTicks(9987),
                            IsDeleted = false,
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = new Guid("1b286cd9-1d18-42ef-8728-b1aa3f2944ec"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 11, DateTimeKind.Local).AddTicks(317),
                            IsDeleted = false,
                            Name = "Gıda"
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3abfb7ed-fe45-4984-9d10-b763447ea129"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 9, DateTimeKind.Local).AddTicks(887),
                            Email = "superadmin@path.com.tr",
                            Firstname = "SuperAdmin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "super123",
                            Phone = "0553 553 5353",
                            UserType = 1
                        },
                        new
                        {
                            Id = new Guid("e04492db-87c8-4a43-9388-965f57362b11"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 10, DateTimeKind.Local).AddTicks(533),
                            Email = "systemadmin@path.com.tr",
                            Firstname = "SystemAdmin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "system123",
                            Phone = "0507 520 4582",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("cb21fad8-3d21-4251-8964-0fac3956322d"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 10, DateTimeKind.Local).AddTicks(550),
                            Email = "admin@path.com.tr",
                            Firstname = "Admin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "admin123",
                            Phone = "0542 652 2358",
                            UserType = 3
                        },
                        new
                        {
                            Id = new Guid("a7545edb-a67a-4dde-9299-4a56d4baba92"),
                            CreatedOn = new DateTime(2022, 5, 13, 4, 28, 20, 10, DateTimeKind.Local).AddTicks(552),
                            Email = "resistablee7@hotmail.com",
                            Firstname = "Selman",
                            IsDeleted = false,
                            Lastname = "KOYAN",
                            Password = "123",
                            Phone = "0553 421 0543",
                            UserType = 4
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.Cargo", b =>
                {
                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", "Company")
                        .WithMany("Cargos")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", "Order")
                        .WithMany("Cargo")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CategoryCargo", b =>
                {
                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", "Category")
                        .WithMany("CategoryCargos")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", "Company")
                        .WithMany("CategoryCargos")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", "Category")
                        .WithMany("Orders")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.User.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("CategoryCargos");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", b =>
                {
                    b.Navigation("CategoryCargos");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.User.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
