// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathOrderManagement.DataAccess;

#nullable disable

namespace PathOrderManagement.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220512214944_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("OrderID");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CargoCompaines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15a46459-5a46-4e34-b67d-3833ff425f52"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 807, DateTimeKind.Local).AddTicks(1549),
                            IsDeleted = false,
                            Name = "Yurtiçi Kargo"
                        },
                        new
                        {
                            Id = new Guid("7c610047-3380-427d-88b7-f2ef397172e1"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 807, DateTimeKind.Local).AddTicks(1864),
                            IsDeleted = false,
                            Name = "Aras Kargo"
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CancellationTokenIsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("615bb4c8-29bf-496f-8453-5a0575fa33c6"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 807, DateTimeKind.Local).AddTicks(3656),
                            IsDeleted = false,
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = new Guid("0cc7ac04-2502-4e52-87a6-5068b3b31b10"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 807, DateTimeKind.Local).AddTicks(3952),
                            IsDeleted = false,
                            Name = "Gıda"
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f96ddac9-8007-457f-af7f-d2fb0e61465f"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 804, DateTimeKind.Local).AddTicks(4349),
                            Email = "superadmin@path.com.tr",
                            Firstname = "SuperAdmin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "super123",
                            Phone = "0553 553 5353",
                            UserType = 1
                        },
                        new
                        {
                            Id = new Guid("7f505752-e71c-418c-a265-38defec99232"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 806, DateTimeKind.Local).AddTicks(2696),
                            Email = "systemadmin@path.com.tr",
                            Firstname = "SystemAdmin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "system123",
                            Phone = "0507 520 4582",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("028dd947-1d6c-4356-b3f1-644ac8c865f6"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 806, DateTimeKind.Local).AddTicks(2711),
                            Email = "admin@path.com.tr",
                            Firstname = "Admin",
                            IsDeleted = false,
                            Lastname = "Path",
                            Password = "admin123",
                            Phone = "0542 652 2358",
                            UserType = 3
                        },
                        new
                        {
                            Id = new Guid("913465b4-13c8-479a-9012-4dd175003162"),
                            CreatedOn = new DateTime(2022, 5, 13, 0, 49, 43, 806, DateTimeKind.Local).AddTicks(2713),
                            Email = "resistablee7@hotmail.com",
                            Firstname = "Selman",
                            IsDeleted = false,
                            Lastname = "KOYAN",
                            Password = "123",
                            Phone = "0553 421 0543",
                            UserType = 4
                        });
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.Cargo", b =>
                {
                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", "Company")
                        .WithMany("Cargo")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", "Order")
                        .WithMany("Cargo")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", "Category")
                        .WithMany("Orders")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathOrderManagement.Entity.DbPathOrderManagement.User.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Cargo.CargoCompanies", b =>
                {
                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.Order", b =>
                {
                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.Order.OrderCategory", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PathOrderManagement.Entity.DbPathOrderManagement.User.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
